### ISSUE TITLE
EclipseLink and Spring-data-dynamodb

### ISSUE THREAD

**Issue by felipefdagaianet** [michaellavelle/spring-data-dynamodb#59]
Hello,

Is there a problem if I use spring-data with EclipseLink (PostgreSQL) mixed with dynamodb with this solution?

I ask cause I configure everything, but my model class is returning:
No [ManagedType] was found for the key class [com.xphub.core.model.Search] in the Metamodel - please verify that the [Managed] class was referenced in persistence.xml using a specific <class>com.xphub.core.model.Search</class> property or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element.

Anyone knows anything about that?

**Comment by derjust** [comment]
@felipefda can you post some more details at https://github.com/derjust/spring-data-dynamodb/issues/16 please?
As (privately) communicated with @michaellavelle, the project will continue under https://github.com/derjust/spring-data-dynamodb.

**Comment by derjust** [comment]
You have to specify which entity class is managed by which repository. Otherwise errors like the one above appear.
An example (with `spring-data-jpa` but it's the same for any `spring-data-*` provider) how to do it is posted at [this fork's wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Multi-Repository-configuration).
